name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: |
          cd web
          npm install
          npm run build
      - uses: actions/checkout@v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          go-version: 1.17
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}